spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    initialization-mode: always
    generate-unique-name: false
  sql:
    init:
      mode: always

  h2:
    console:
      enabled: true
      path: /h2-console

  mybatis:
    mapper-locations: classpath:mapper/*.xml
    config-location: classpath:mybatis-config.xml
    configuration:
      map-underscore-to-camel-case: true




